on: [ push, pull_request ]

permissions:
  pull-requests: write

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    name: Smoke Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: diffctx
        uses: williamfzc/diffctx@v0.2.3
        with:
          lang: "python"
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}